### ISSUE TITLE
Get global Id of record when executing a mutation

### ISSUE THREAD

**Issue by alexisrolland** [graphql-python/graphene-sqlalchemy#108]
Hello,

I have found zero documentation nor help on this topic so I'm posting it here with the hope to get some support. It's not a bug per say but rather a question. Apologies in advance if you find it inappropriate.

In short, I have implemented a mutation to create a new record and I would like to get the global Id of this record in the response from the API:

```python
from graphql_relay.node.node import to_global_id
import api_utils
import batch_schema
import graphene


class CreateBatchOwnerInput(graphene.InputObjectType):
    """Input to create batch owner."""
    name = graphene.String(required=True)


class CreateBatchOwner(graphene.Mutation):
    """Create batch owner."""
    class Arguments:
        input = CreateBatchOwnerInput(required=True)

    # Class attributes
    batch_owner = graphene.Field(batch_schema.BatchOwner)

    @staticmethod
    def mutate(root, info, input=None):
        """Method to create batch owner."""
        record = {'name': input.name}
        batch_owner = api_utils.create('BatchOwner', record)  # This returns a dictionary {'id': int, 'name': string}
        batch_owner = batch_schema.BatchOwner(**batch_owner)
        batch_owner.id = to_global_id('BatchOwner', batch_owner.id)  # Convert database Id to global Id
        return CreateBatchOwner(batch_owner=batch_owner)
```

The following mutation works fine
```
mutation Mutation {
    createBatchOwner(input: {name:"Jake"}) {
        batchOwner {
          name
        }
    }
}

response:

{
  "data": {
    "createBatchOwner": {
      "batchOwner": {
        "name": "Jake"
      }
    }
  }
}
```

But when I add the "id" field in the payload I get the following error message:
```
mutation Mutation {
    createBatchOwner(input: {name:"Antoine"}) {
        batchOwner {
          id
          name
        }
    }
}

response:

{
  "data": {
    "createBatchOwner": {
      "batchOwner": null
    }
  },
  "errors": [
    {
      "message": "'BatchOwner' object has no attribute '__mapper__'",
      "locations": [
        {
          "column": 11,
          "line": 4
        }
      ]
    }
  ]
}
```

Here is the log generated by the Flask application:
```
Traceback (most recent call last):
  File "/home/alexis/data-quality-venv/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/home/alexis/data-quality-venv/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
  File "/home/alexis/data-quality-venv/lib/python3.5/site-packages/graphene/relay/node.py", line 38, in id_resolver
    type_id = parent_resolver(root, info, **args)
  File "/home/alexis/data-quality-venv/lib/python3.5/site-packages/graphene_sqlalchemy/types.py", line 160, in resolve_id
    keys = self.__mapper__.primary_key_from_instance(self)
AttributeError: 'BatchOwner' object has no attribute '__mapper__'
Traceback (most recent call last):
  File "/home/alexis/data-quality-venv/lib/python3.5/site-packages/graphql/execution/executor.py", line 330, in complete_value_catching_error
    exe_context, return_type, field_asts, info, result)
  File "/home/alexis/data-quality-venv/lib/python3.5/site-packages/graphql/execution/executor.py", line 405, in complete_value
    return complete_object_value(exe_context, return_type, field_asts, info, result)
  File "/home/alexis/data-quality-venv/lib/python3.5/site-packages/graphql/execution/executor.py", line 504, in complete_object_value
    return execute_fields(exe_context, return_type, result, subfield_asts)
  File "/home/alexis/data-quality-venv/lib/python3.5/site-packages/graphql/execution/executor.py", line 148, in execute_fields
    source_value, field_asts)
  File "/home/alexis/data-quality-venv/lib/python3.5/site-packages/graphql/execution/executor.py", line 247, in resolve_field
    result
  File "/home/alexis/data-quality-venv/lib/python3.5/site-packages/graphql/execution/executor.py", line 324, in complete_value_catching_error
    return complete_value(exe_context, return_type, field_asts, info, result)
  File "/home/alexis/data-quality-venv/lib/python3.5/site-packages/graphql/execution/executor.py", line 383, in complete_value
    raise GraphQLLocatedError(field_asts, original_error=result)
graphql.error.located_error.GraphQLLocatedError: 'BatchOwner' object has no attribute '__mapper__'
```

**Comment by alexisrolland** [comment]
Not sure what was the issue but this worked for me:

```python
from database.operation import Operation
import api_utils
import batch_schema
import graphene
import logging

# Load logging configuration
log = logging.getLogger(__name__)


class CreateBatchOwnerInput(graphene.InputObjectType):
    """Arguments to create a batch owner."""
    name = graphene.String(required=True)


class CreateBatchOwner(graphene.Mutation):
    """Mutation to create a batch owner."""
    # Declare class attributes
    batch_owner = graphene.Field(batch_schema.BatchOwner)

    class Arguments:
        input = CreateBatchOwnerInput(required=True)

    def mutate(self, info, input):
        """Mutation to create a batch owner."""
        # Convert input to dictionary
        data = api_utils.input_to_dictionary(input)
        batch_owner = Operation('BatchOwner').create(**data)
        return CreateBatchOwner(batch_owner=batch_owner)
```
